/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useEffect, useState, useRef } from 'react';
import type { Receipt } from './types';
import { jsPDF } from 'jspdf';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from 'recharts';

export default function App() {
  const [receipts, setReceipts] = useState<Receipt[]>([]);
  const [selectedReceipt, setSelectedReceipt] = useState<Receipt | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    fetchReceipts();
  }, []);

  const fetchReceipts = async () => {
    try {
      const res = await fetch('/api/receipts');
      if (!res.ok) {
        const text = await res.text();
        if (text.includes('relation "receipts" does not exist')) {
            setError('The "receipts" table does not exist in your Supabase project. Please create it manually.');
            return;
        }
        throw new Error('Failed to fetch receipts');
      }
      const data = await res.json();
      if (data.receipts) {
        setReceipts(data.receipts);
        if (data.receipts.length > 0 && !selectedReceipt) {
          setSelectedReceipt(data.receipts[0]);
        }
      }
    } catch (err: any) {
      setError(err.message || String(err));
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    setError('');

    try {
      const getBase64 = (file: File): Promise<string> => {
        return new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.readAsDataURL(file);
          reader.onload = () => {
             const base64Data = reader.result?.toString().split(',')[1];
             if (base64Data) resolve(base64Data);
             else reject(new Error('Failed to parse file base64'));
          };
          reader.onerror = error => reject(error);
        });
      };

      const base64Data = await getBase64(file);

      const res = await fetch('/api/receipts/process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ imageBase64: base64Data, mimeType: file.type })
      });

      let data;
      try {
        data = await res.json();
      } catch (e) {
        throw new Error('Server returned an invalid response. The file might be too large.');
      }
      
      if (!res.ok) {
          if (data.error?.includes('relation "receipts" does not exist') || data.error?.includes('relation "public.receipts" does not exist')) {
              throw new Error('The "receipts" table does not exist in your Supabase database. Please create it first.');
          }
          throw new Error(data.error || 'Failed to process receipt');
      }

      if (data.receipt) {
        setReceipts(prev => [data.receipt, ...prev]);
        setSelectedReceipt(data.receipt);
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsUploading(false);
    }
  };

  const calculateTotal = () => receipts.reduce((acc, r) => acc + (r.total || 0), 0);
  const calculateTVA = () => receipts.reduce((acc, r) => acc + (r.tva || 0), 0);

  const getCategoryData = () => {
    const categoryTotals: Record<string, number> = {};
    receipts.forEach(r => {
      const cat = r.category || 'Uncategorized';
      categoryTotals[cat] = (categoryTotals[cat] || 0) + (r.total || 0);
    });
    return Object.entries(categoryTotals).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
  };

  const categoryData = getCategoryData();
  const COLORS = ['#FF6B00', '#4CAF50', '#2196F3', '#9C27B0', '#FFC107', '#00BCD4', '#795548', '#607D8B'];

  const downloadPDF = () => {
    if (!selectedReceipt) return;

    const doc = new jsPDF();
    const { merchant, date, category, total, currency, ht, tva, id } = selectedReceipt;
    const ref = id.substring(0, 8).toUpperCase();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("Receipt Export", 20, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Generated by ReceiptAI", 20, 28);
    
    doc.setDrawColor(200);
    doc.setFillColor(250, 250, 250);
    doc.roundedRect(20, 40, 170, 100, 3, 3, "FD");

    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(merchant || "Unknown Merchant", 30, 55);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(`Transaction Ref: ${ref} • ${date}`, 30, 62);

    doc.line(30, 70, 180, 70);

    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    doc.text("Category", 30, 85);
    doc.setFont("helvetica", "normal");
    doc.text(category || "Uncategorized", 70, 85);

    doc.setFont("helvetica", "bold");
    doc.text("Amount HT", 30, 95);
    doc.setFont("helvetica", "normal");
    doc.text(`${ht ? ht.toFixed(2) : '---'} ${currency || 'DH'}`, 70, 95);

    doc.setFont("helvetica", "bold");
    doc.text("TVA", 30, 105);
    doc.setFont("helvetica", "normal");
    doc.text(`${tva ? tva.toFixed(2) : '---'} ${currency || 'DH'}`, 70, 105);

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("TOTAL:", 30, 125);
    doc.text(`${total ? total.toFixed(2) : '---'} ${currency || 'DH'}`, 70, 125);

    doc.save(`ReceiptAI_${ref}_${(merchant || 'receipt').replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#0A0A0A] text-gray-100 font-sans flex flex-col overflow-hidden">
      {/* Header Navigation */}
      <header className="flex items-center justify-between px-8 py-6 border-b border-white/5">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-[#FF6B00] rounded-xl flex items-center justify-center shadow-lg shadow-[#FF6B00]/20">
            <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6 text-black" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Receipt<span className="text-[#FF6B00]">AI</span></h1>
        </div>
        <div className="flex items-center gap-6">
          <div className="flex bg-white/5 p-1 rounded-lg">
            <button className="px-4 py-1.5 rounded-md bg-[#FF6B00] text-black font-semibold text-sm cursor-pointer">October</button>
            <button className="px-4 py-1.5 rounded-md text-gray-400 hover:text-gray-200 font-medium text-sm cursor-pointer transition-colors">September</button>
          </div>
          <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-gray-700 to-gray-600 border border-white/10 cursor-pointer"></div>
        </div>
      </header>

      {/* Dashboard Layout */}
      <main className="flex-1 p-8 grid grid-cols-1 md:grid-cols-12 gap-8 overflow-y-auto">
        {/* Left Column: Statistics */}
        <aside className="md:col-span-4 lg:col-span-3 flex flex-col gap-6">
          <div className="bg-white/5 border border-white/10 rounded-3xl p-6">
            <p className="text-xs font-bold uppercase tracking-widest text-[#FF6B00] mb-1">Monthly Total</p>
            <h2 className="text-4xl font-light text-white">{calculateTotal().toFixed(2)} <span className="text-xl opacity-50">MAD</span></h2>
            <div className="mt-4 flex items-center gap-2 text-green-400 text-sm">
              <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" />
              </svg>
              <span>12% from last month</span>
            </div>
          </div>

          <div className="bg-white/5 border border-white/10 rounded-3xl p-6">
            <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-1">TVA Récupérable</p>
            <h2 className="text-3xl font-medium text-white">{calculateTVA().toFixed(2)} <span className="text-lg opacity-50">MAD</span></h2>
            <div className="w-full bg-white/10 h-1.5 rounded-full mt-4 overflow-hidden">
              <div className="bg-[#FF6B00] h-full" style={{ width: '65%' }}></div>
            </div>
            <p className="text-[11px] text-gray-500 mt-2">65% of deductible limit reached</p>
          </div>

          {receipts.length > 0 && (
            <div className="bg-white/5 border border-white/10 rounded-3xl p-6">
              <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-4">Spending by Category</p>
              <div className="h-48 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={categoryData}
                      cx="50%"
                      cy="50%"
                      innerRadius={60}
                      outerRadius={80}
                      paddingAngle={5}
                      dataKey="value"
                      stroke="none"
                    >
                      {categoryData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip 
                      formatter={(value: number) => [`${value.toFixed(2)}`, 'Amount']}
                      contentStyle={{ backgroundColor: '#1A1A1A', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '12px', color: '#fff' }}
                      itemStyle={{ color: '#fff' }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          <div className="flex-1 bg-white/5 border border-white/10 rounded-3xl p-6 overflow-y-auto max-h-[600px] no-scrollbar">
            <h3 className="text-sm font-semibold mb-4 flex items-center gap-2">
              <span className="w-1.5 h-4 bg-[#FF6B00] rounded-full"></span>
              Recent Extractions
            </h3>
            <div className="space-y-4">
              {receipts.length === 0 ? (
                <p className="text-sm text-gray-500">No receipts found. Upload one to get started.</p>
              ) : receipts.map(receipt => (
                 <div 
                   key={receipt.id} 
                   onClick={() => setSelectedReceipt(receipt)}
                   className={`flex items-center justify-between p-3 rounded-2xl cursor-pointer transition-colors ${selectedReceipt?.id === receipt.id ? 'bg-white/10 border border-white/10' : 'bg-white/5 hover:bg-white/10'}`}
                 >
                   <div className="flex flex-col">
                     <span className="text-sm font-medium">{receipt.merchant || 'Unknown Merchant'}</span>
                     <span className="text-[10px] text-gray-500">{receipt.date} • {receipt.category}</span>
                   </div>
                   <span className="text-sm font-bold">{receipt.total?.toFixed(2) || '0.00'} {receipt.currency || 'DH'}</span>
                 </div>
              ))}
            </div>
          </div>
        </aside>

        {/* Right Column: Workspace */}
        <div className="md:col-span-8 lg:col-span-9 flex flex-col gap-6">
          {error && (
            <div className="bg-red-500/10 border border-red-500/50 text-red-500 p-4 rounded-xl text-sm whitespace-pre-wrap">
              {error}
            </div>
          )}
          
          <div 
            onClick={() => fileInputRef.current?.click()}
            className="relative group flex flex-col items-center justify-center border-2 border-dashed border-white/10 hover:border-[#FF6B00]/40 bg-white/[0.02] rounded-3xl p-12 transition-all cursor-pointer overflow-hidden"
          >
            <input 
              type="file" 
              accept="image/*,application/pdf" 
              className="hidden" 
              ref={fileInputRef} 
              onChange={handleFileUpload} 
              disabled={isUploading}
            />
            <div className="absolute inset-0 bg-[#FF6B00]/5 opacity-0 group-hover:opacity-100 transition-opacity"></div>
            <div className="w-14 h-14 rounded-full bg-[#FF6B00]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              {isUploading ? (
                <div className="w-6 h-6 border-2 border-[#FF6B00] border-t-transparent rounded-full animate-spin"></div>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" className="w-7 h-7 text-[#FF6B00]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                </svg>
              )}
            </div>
            <p className="text-lg font-medium text-white group-hover:text-[#FF6B00] transition-colors">{isUploading ? 'Extracting via AI...' : 'Drag & drop or tap to scan'}</p>
            <p className="text-sm text-gray-500 mt-1">Supports JPG, PNG or PDF files</p>
          </div>

          <div className="flex-1 bg-white/5 border border-white/10 rounded-3xl p-8 flex flex-col">
            {selectedReceipt ? (
              <>
                <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between mb-8 gap-4">
                  <div>
                    <span className="px-3 py-1 bg-green-500/10 text-green-500 text-[10px] font-bold uppercase tracking-wider rounded-full">AI Processed Successfully</span>
                    <h3 className="text-2xl font-bold mt-4 text-white">{selectedReceipt.merchant || 'Unknown Merchant'}</h3>
                    <p className="text-gray-500 text-sm mt-1">Transaction Ref: {selectedReceipt.id.substring(0, 8).toUpperCase()} • {selectedReceipt.date}</p>
                  </div>
                  <button onClick={downloadPDF} className="px-5 py-2.5 bg-[#FF6B00]/10 hover:bg-[#FF6B00]/20 text-[#FF6B00] border border-[#FF6B00]/20 rounded-xl text-sm font-medium transition-colors cursor-pointer w-full lg:w-auto">Download as PDF</button>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
                  <div className="space-y-6">
                    <div>
                      <p className="text-[10px] uppercase font-bold text-gray-500 mb-1">Category</p>
                      <p className="text-sm font-medium">{selectedReceipt.category || 'Uncategorized'}</p>
                    </div>
                    <div>
                      <p className="text-[10px] uppercase font-bold text-gray-500 mb-1">Status</p>
                      <p className="text-sm font-medium flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-blue-400 shadow-[0_0_8px_rgba(96,165,250,0.5)]"></span>
                        {selectedReceipt.status || 'Pending'}
                      </p>
                    </div>
                  </div>
                  
                  {selectedReceipt.insight && (
                    <div className="lg:col-span-2 bg-black/40 rounded-2xl p-5 border border-white/5 flex flex-col justify-center">
                      <div className="flex items-center gap-3 mb-4">
                        <div className="w-6 h-6 rounded-md bg-[#FF6B00] flex items-center justify-center shadow-lg shadow-[#FF6B00]/20">
                          <svg xmlns="http://www.w3.org/2000/svg" className="w-3.5 h-3.5 text-black" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M11 3a1 1 0 10-2 0v1a1 1 0 102 0V3zM15.657 5.757a1 1 0 00-1.414-1.414l-.707.707a1 1 0 001.414 1.414l.707-.707zM18 10a1 1 0 01-1 1h-1a1 1 0 110-2h1a1 1 0 011 1zM5.05 6.464A1 1 0 106.464 5.05l-.707-.707a1 1 0 00-1.414 1.414l.707.707zM5 10a1 1 0 01-1 1H3a1 1 0 110-2h1a1 1 0 011 1zM8 16v-1a1 1 0 112 0v1a1 1 0 11-2 0zM13.536 14.243a1 1 0 011.414 1.414l-.707.707a1 1 0 01-1.414-1.414l.707-.707zM16 18a1 1 0 100-2 1 1 0 000 2z" />
                          </svg>
                        </div>
                        <p className="text-xs font-bold uppercase tracking-wide text-[#FF6B00]">Gemini AI Insight</p>
                      </div>
                      <p className="text-sm leading-relaxed text-gray-300 italic">"{selectedReceipt.insight}"</p>
                    </div>
                  )}
                </div>

                {/* TVA Breakdown */}
                <div className="mt-auto flex flex-col sm:flex-row items-start sm:items-end justify-between border-t border-white/5 pt-6 gap-6 sm:gap-0">
                  <div className="flex gap-8 sm:gap-12 w-full sm:w-auto">
                    <div>
                      <p className="text-xs text-gray-500 mb-1">Montant HT</p>
                      <p className="text-xl font-medium text-white">{selectedReceipt.ht ? selectedReceipt.ht.toFixed(2) : '---'} <span className="text-sm opacity-40">{selectedReceipt.currency || 'DH'}</span></p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 mb-1">TVA (20%)</p>
                      <p className="text-xl font-medium text-white">{selectedReceipt.tva ? selectedReceipt.tva.toFixed(2) : '---'} <span className="text-sm opacity-40">{selectedReceipt.currency || 'DH'}</span></p>
                    </div>
                  </div>
                  <div className="text-left sm:text-right w-full sm:w-auto">
                    <p className="text-xs text-[#FF6B00] font-bold mb-1 tracking-wider">TOTAL TTC</p>
                    <p className="text-4xl font-bold text-white">{selectedReceipt.total ? selectedReceipt.total.toFixed(2) : '---'} <span className="text-lg opacity-40">{selectedReceipt.currency || 'DH'}</span></p>
                  </div>
                </div>
              </>
            ) : (
              <div className="flex items-center justify-center h-full text-gray-500">
                <p>Select or scan a receipt to view details</p>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Sticky Mobile-vibe Actions Dock */}
      <footer className="px-8 py-6 pb-8 flex justify-center fixed bottom-0 w-full pointer-events-none">
        <div className="bg-[#1A1A1A] border border-white/10 px-8 py-3 rounded-full flex items-center gap-10 shadow-2xl pointer-events-auto">
          <button className="text-[#FF6B00] hover:scale-110 transition-transform cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
          </button>
          <button className="text-gray-500 hover:text-gray-200 hover:scale-110 transition-all cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
            </svg>
          </button>
          <div 
             onClick={() => fileInputRef.current?.click()}
             className="w-10 h-10 bg-[#FF6B00] rounded-full flex items-center justify-center transform hover:scale-110 cursor-pointer shadow-[0_0_20px_rgba(255,107,0,0.4)] transition-all"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-black" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
            </svg>
          </div>
          <button className="text-gray-500 hover:text-gray-200 hover:scale-110 transition-all cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
            </svg>
          </button>
          <button className="text-gray-500 hover:text-gray-200 hover:scale-110 transition-all cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
          </button>
        </div>
      </footer>
    </div>
  );
}
